// "use client";

import "./globals.css";
import "sweetalert2/src/sweetalert2.scss";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import Newsletter from "./components/Newsletter/Newsletter";
import Layout from "./components/Layout/Layout";
import HearthMotionInitializer from "./components/HearthMotionInitializer/HearthMotionInitializer";
import AosLenisProvider from "./components/AosWrapper/AosWrapper";
import Script from "next/script";

export const metadata = {
  title: "Consultiqo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // useHearthMotion();
  return (
    <html lang="en">
      <head>
        {/* <link
          rel="stylesheet"
          href=""
        /> */}
      </head>
      <body>
        <HearthMotionInitializer />
        <Navbar />
        {children}
        <Newsletter />
        <Footer />
      </body>

      {/* <Script
        src="http://127.0.0.1:5500/hearthmotion-core.js"
        strategy="afterInteractive"
      /> */}

      {/* <Script
        src="https://cdn.jsdelivr.net/gh/shakib-mia/hearthmotion-npm@main/src/hearthmotion.js"
        type="module"
      ></Script> */}
    </html>
  );
}
